[package]
name = "spider"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.53", features = ["derive"] }
ring = "0.17.14"
tokio = { version = "1.48.0", features = ["full"] }
urlencoding = "2.1.3"